create database logs;

CREATE TABLE logs(
	id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	ip varchar(17) not null,
	created_at timestamp,
	gmt varchar(6),
	request varchar(20),
	adress varchar,
	http varchar(16),
	code int,
	bytes int
);
